repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml # Attempts to load all yaml files to verify syntax
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline

  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check django app for missing migrations
        entry: sh -c "./app/manage.py makemigrations --check --dry-run"
        files: "models"
