# Generated by Django 4.2.5 on 2023-09-30 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('level', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitutionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('education_level_on_graduation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_institution_types', to='education.educationallevel')),
                ('required_educational_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='education.educationallevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='education.educationalinstitutiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
